version: "3"

services:

  # CakePHP, Nginx, PHP
  template-web:
    container_name: template-web
    volumes:
      - "../doc/development/nginx:/etc/nginx/"
      - "../doc/development/php-fpm/php-fpm.d:/etc/php-fpm.d/"
      - "../:/export/www/docker-template"
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "80:80"

  # PostgreSQL
  template-db:
    container_name: template-db
    volumes:
      - "../:/export/www/docker-template"
      - "./db/pgdata:/export/pgdata:z"
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "15432:5432"
